version: '3.8'

services:
  app:
    image: laravelsail/php83-composer:latest
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: php artisan serve --host=0.0.0.0 --port=8080
    depends_on:
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  vite:
    image: node:20
    container_name: laravel_vite
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge